export const AUTOCORRECT_DICT: Record<string, string> = {
  'teh': 'the', 'recieve': 'receive', 'occured': 'occurred', 'seperate': 'separate',
  'definately': 'definitely', 'accomodate': 'accommodate', 'acheive': 'achieve',
  'accross': 'across', 'agressive': 'aggressive', 'apparantly': 'apparently',
  'arguement': 'argument', 'assasination': 'assassination', 'basicly': 'basically',
  'begining': 'beginning', 'beleive': 'believe', 'bizzare': 'bizarre',
  'buisness': 'business', 'calender': 'calendar', 'camoflage': 'camouflage',
  'catagory': 'category', 'cemetary': 'cemetery', 'changable': 'changeable',
  'colleage': 'colleague', 'comming': 'coming', 'commited': 'committed',
  'comparitively': 'comparatively', 'concensus': 'consensus', 'consciencious': 'conscientious',
  'concious': 'conscious', 'consistant': 'consistent', 'coperate': 'cooperate',
  'correspondance': 'correspondence', 'critisize': 'criticize', 'decieve': 'deceive',
  'definite': 'definite', 'desparate': 'desperate', 'develope': 'develop',
  'diffrence': 'difference', 'dilema': 'dilemma', 'disapear': 'disappear',
  'disapoint': 'disappoint', 'dissapear': 'disappear', 'ecstacy': 'ecstasy',
  'embarass': 'embarrass', 'enviroment': 'environment', 'exagerate': 'exaggerate',
  'excercise': 'exercise', 'existance': 'existence', 'experiance': 'experience',
  'facinate': 'fascinate', 'firey': 'fiery', 'flourescent': 'fluorescent',
  'foriegn': 'foreign', 'freind': 'friend', 'fulfil': 'fulfill',
  'goverment': 'government', 'grammer': 'grammar', 'gaurd': 'guard',
  'harrass': 'harass', 'heighth': 'height', 'heros': 'heroes',
  'humourous': 'humorous', 'hygeine': 'hygiene', 'ignorence': 'ignorance',
  'immediatly': 'immediately', 'incidently': 'incidentally', 'independant': 'independent',
  'innoculate': 'inoculate', 'intellegent': 'intelligent', 'intresting': 'interesting',
  'irresistable': 'irresistible', 'jeapordize': 'jeopardize', 'jewelery': 'jewelry',
  'judgement': 'judgment', 'knowlege': 'knowledge', 'liason': 'liaison',
  'libary': 'library', 'liesure': 'leisure', 'lightening': 'lightning',
  'maintainance': 'maintenance', 'manuever': 'maneuver', 'medeval': 'medieval',
  'millenium': 'millennium', 'minature': 'miniature', 'mischevious': 'mischievous',
  'mispell': 'misspell', 'necassary': 'necessary', 'neccessary': 'necessary',
  'negligable': 'negligible', 'negociate': 'negotiate', 'nieghbor': 'neighbor',
  'noticable': 'noticeable', 'occurence': 'occurrence', 'omision': 'omission',
  'oppurtunity': 'opportunity', 'outragous': 'outrageous', 'parliment': 'parliament',
  'passtime': 'pastime', 'percieve': 'perceive', 'perseverence': 'perseverance',
  'personel': 'personnel', 'pharoah': 'pharaoh', 'pigeon': 'pigeon',
  'plagarize': 'plagiarize', 'posession': 'possession', 'potatos': 'potatoes',
  'preceed': 'precede', 'presance': 'presence', 'privelege': 'privilege',
  'profesor': 'professor', 'pronounciation': 'pronunciation', 'publically': 'publicly',
  'questionaire': 'questionnaire', 'readible': 'readable', 'realy': 'really',
  'refered': 'referred', 'referance': 'reference', 'religous': 'religious',
  'repitition': 'repetition', 'resistence': 'resistance', 'restaraunt': 'restaurant',
  'rythm': 'rhythm', 'sacrilegious': 'sacrilegious', 'sargent': 'sergeant',
  'satisfactoraly': 'satisfactorily', 'shedule': 'schedule', 'sieze': 'seize',
  'sentance': 'sentence', 'sargant': 'sergeant', 'sincerly': 'sincerely',
  'speach': 'speech', 'succesful': 'successful', 'supercede': 'supersede',
  'surprize': 'surprise', 'temperture': 'temperature', 'threshhold': 'threshold',
  'tommorow': 'tomorrow', 'tommorrow': 'tomorrow', 'tounge': 'tongue',
  'truely': 'truly', 'tyrany': 'tyranny', 'underate': 'underrate',
  'untill': 'until', 'upholstry': 'upholstery', 'useable': 'usable',
  'vaccuum': 'vacuum', 'vegetable': 'vegetable', 'vengance': 'vengeance',
  'vigilence': 'vigilance', 'visious': 'vicious', 'wether': 'whether',
  'wierd': 'weird', 'writting': 'writing', 'yeild': 'yield',
  'abotu': 'about', 'adn': 'and', 'ahve': 'have', 'amke': 'make',
  'aobut': 'about', 'aslo': 'also', 'becuase': 'because', 'befoer': 'before',
  'casue': 'cause', 'chnage': 'change', 'coudl': 'could', 'diong': 'doing',
  'doesnt': "doesn't", 'dont': "don't", 'eahc': 'each', 'evrey': 'every',
  'fomr': 'from', 'fo': 'of', 'gonig': 'going', 'hvae': 'have',
  'htat': 'that', 'htey': 'they', 'hten': 'then', 'hwen': 'when',
  'iwth': 'with', 'jsut': 'just', 'knwo': 'know', 'liek': 'like',
  'mkae': 'make', 'nkow': 'know', 'nto': 'not', 'otehr': 'other',
  'owrk': 'work', 'poeple': 'people', 'rela': 'real', 'shoudl': 'should',
  'smae': 'same', 'soem': 'some', 'stnad': 'stand', 'taht': 'that',
  'tahn': 'than', 'thier': 'their', 'thsi': 'this', 'tihs': 'this',
  'tiem': 'time', 'waht': 'what', 'whcih': 'which', 'whta': 'what',
  'wnat': 'want', 'wokr': 'work', 'wolud': 'would', 'wtih': 'with',
  'yera': 'year', 'yuor': 'your',
  'abscence': 'absence', 'abundence': 'abundance', 'accidentaly': 'accidentally',
  'ackowledge': 'acknowledge', 'acquaintence': 'acquaintance', 'adquate': 'adequate',
  'advantagous': 'advantageous', 'alot': 'a lot', 'amatuer': 'amateur',
  'annonymous': 'anonymous', 'apparant': 'apparent', 'apropriate': 'appropriate',
  'artic': 'arctic', 'awfull': 'awful', 'beautifull': 'beautiful',
  'begginer': 'beginner', 'belive': 'believe', 'benifit': 'benefit',
  'bouyant': 'buoyant', 'breif': 'brief', 'brillant': 'brilliant',
  'bulitin': 'bulletin', 'burgler': 'burglar', 'calandar': 'calendar',
  'cannidate': 'candidate', 'carribean': 'caribbean', 'chauffer': 'chauffeur',
  'colum': 'column', 'comemorate': 'commemorate', 'compatable': 'compatible',
  'completly': 'completely', 'conceed': 'concede', 'congradulate': 'congratulate',
  'contientious': 'conscientious', 'controvercial': 'controversial', 'convienient': 'convenient',
  'corageous': 'courageous', 'counterfiet': 'counterfeit', 'curiousity': 'curiosity',
  'decathalon': 'decathlon', 'definate': 'definite',
};

export function checkAutocorrect(word: string): string | null {
  const lower = word.toLowerCase();
  return AUTOCORRECT_DICT[lower] || null;
}
